#!/bin/sh

# Збірка всіх компонентів (обидві версії титулки + решта документів)
latexmk -pdflatex='xelatex %O %S' -pdf project-title.tex project-title-v2.tex specification.tex tech-task.tex thesis.tex annex-s.tex annex-f.tex annex-alg.tex annex-p.tex

# Повний диплом з титулкою Версії 1
#gs -dNOPAUSE -sDEVICE=pdfwrite -sOUTPUTFILE=full-diploma.pdf -dBATCH project-title.pdf specification.pdf tech-task.pdf thesis.pdf annex-s.pdf annex-f.pdf annex-alg.pdf annex-p.pdf

# Повний диплом з титулкою Версії 2
gs -dNOPAUSE -sDEVICE=pdfwrite -sOUTPUTFILE=full-diploma-v2.pdf -dBATCH project-title-v2.pdf specification.pdf tech-task.pdf thesis.pdf annex-s.pdf annex-f.pdf annex-alg.pdf annex-p.pdf
